baseURL = 'https://trylifeinweeks.github.io/'
languageCode = 'en-us'
title = 'Life in Weeks – Hanhee Lee'
disableKinds = ["taxonomy", "taxonomy"]
enableEmoji = true
enableRobotsTXT = true


[params]
name = "Hanhee Lee"
birthdate = "2004-12-04"
author = "Hanhee Lee"

[caches]
[caches.images]
dir = ":cacheDir/images"
